// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PlaySound(arg1) {
  return window['go']['main']['App']['PlaySound'](arg1);
}

export function StartReceiver() {
  return window['go']['main']['App']['StartReceiver']();
}

export function StartReceiverDefault() {
  return window['go']['main']['App']['StartReceiverDefault']();
}

export function StartSender() {
  return window['go']['main']['App']['StartSender']();
}

export function StopReceiver() {
  return window['go']['main']['App']['StopReceiver']();
}

export function StopSender() {
  return window['go']['main']['App']['StopSender']();
}
