// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile(arg1:string):Promise<string>;

export function PlaySound(arg1:string):Promise<void>;

export function StartReceiver():Promise<string>;

export function StartReceiverDefault():Promise<string>;

export function StartSender():Promise<string>;

export function StopReceiver():Promise<string>;

export function StopSender():Promise<string>;
